api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
    url(r'^pets/$', views.ListSongs.as_view(), name='list_songs'),
    url(r'^cities/$', views.GroupList.as_view(), name='list_song'),
]

pets/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.contrib import admin


urlpatterns = [
    url(r'^pets/', include('song.urls', namespace='song')),
    url(r'^social/', include('social_django.urls', namespace='social')),
    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('common.urls', namespace='common')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

song/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.SongIndexView.as_view(), name='index'),
    url(r'^new/$', views.RegisterSongView.as_view()),
    url(r'^search/$', views.SearchView.as_view()),
    url(r'^novo/$', views.RegisterSongView.as_view(), name='register'),
    url(r'^busca/$', views.SearchView.as_view(), name='search'),
    url(r'^atualizar-cadastro/(?P<request_key>\w+)/$', views.update_register, name='update_register'),
    url(r'^pet/(?P<slug>[-\w]*)/foto/$', views.upload_image, name='upload_image'),
    url(r'^(?P<slug>[-\w]*)/editar/$', views.EditSongView.as_view(), name='edit'),
    url(r'^(?P<slug>[-\w]*)/poster/$', views.poster, name='poster'),
    url(r'^(?P<slug>[-\w]*)/editar/situacao/$', views.change_status, name='change_status'),
    url(r'^(?P<slug>[-\w]*)/deletar/$', views.delete_song, name='delete_pet'),
    url(r'^(?P<slug>[-\w]*)/registrado/$', views.registered, name='registered'),

    url(r'^(?P<pk_or_slug>[-\w]*)/$', views.song_detail_view, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.song_detail_view, name='detail_by_pk'),
]

users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.CreateUserView.as_view(), name='create'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.ProfileDetailView.as_view(), name='user_profile'),
    url(r'^profile/$', views.UserProfileView.as_view(), name='profile'),
    url(r'^profile/edit/$', views.EditUserProfileView.as_view(), name='edit'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^confirm/$', views.confirm_information, name='confirm_information'),
    url(r'^recover/$', views.RecoverView.as_view(), name='recover_password'),
    url(r'^recover/reset/done/$', views.RecoverResetDoneView.as_view(), name='recover_password_done'),
    url(r'^recover/reset/(?P<token>.+)/$', views.RecoverResetView.as_view(), name='recover_password_reset'),
    url(r'^recover/(?P<signature>.+)/$', views.RecoverDoneView.as_view(), name='recover_password_sent'),
]

song/models.py
import hashlib

from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone, crypto
from django.utils.text import slugify

from autoslug import AutoSlugField
from django_extensions.db.models import TimeStampedModel

from song import services
from users.models import OwnerProfile


class SongQuerySet(models.QuerySet):

    def get_unpublished_pets(self):
        return self.filter(published=False)


class Group(models.Model):
    name = models.TextField(max_length=100, unique=True)
    genre = models.TextField(max_length=100)
    slug = AutoSlugField(max_length=30)
    image = models.ImageField(upload_to='group_photos')

    def __str__(self):
        return self.name


def get_slug(instance):
    group = ''
    if instance.group:
        group = instance.city.name
    return slugify('{}-{}'.format(instance.name, group))


class Song(TimeStampedModel):
    owner = models.ForeignKey(OwnerProfile)
    group = models.ForeignKey(Group)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)

    slug = AutoSlugField(max_length=50, populate_from=get_slug, unique=True)

    objects = SongQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse('song:detail', kwargs={'pk_or_slug': get_slug})

    def request_action(self):
        hash_input = (crypto.get_random_string(5) + self.name).encode('utf-8')
        self.request_key = hashlib.sha1(hash_input).hexdigest()

        if not services.send_request_action_email(self):
            return

        self.request_sent = timezone.now()
        self.save(update_modified=False)

        self.active = False
        self.save(update_modified=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-id']


class Photo(models.Model):
    group = models.ForeignKey(Group)
    image = models.ImageField(upload_to='group_photos')


# CREATE TABLE test_songs (id int, song_name VARCHAR(50), group_name VARCHAR(50), song_text VARCHAR(2000),


# class Songs(models.Model):
#     song_name = models.CharField(max_length=50)
#     group_name = models.CharField(max_length=50)
#     song_text = models.CharField(max_length=2000)
#     song_accords = models.CharField(max_length=100)

# CREATE TABLE test_groups (id INT, group_name VARCHAR(50), genre VARCHAR(50), group_members VARCHAR(200),
# image_url VARCHAR(250), description VARCHAR(500));

# class Groups(models.Model):
    #     group_name = models.CharField(max_length=50)
    #     genre = models.CharField(max_length=50)
    #     group_members = models.CharField(max_length=50)
    #     image_url = models.CharField(max_length=50)
    #     description = models.CharField(max_length=500)

song/forms.py
from django import forms
from django.utils.translation import ugettext as _

from song import models


# def _build_choice_field(label, choices=None, required=False):
#     empty_choice = (('', '------------'),)
#     field = forms.ChoiceField(
#         widget=forms.Select(attrs={'class': 'form-control'}),
#         choices=empty_choice,
#         label=label,
#         required=required
#     )
#     if choices:
#         field.choices += choices
#     return field


class SongForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        initial = kwargs.pop('initial', {})
        kwargs['initial'] = initial
        super(SongForm, self).__init__(*args, **kwargs)

    class Meta:
        model = models.Song
        fields = ('name', 'group', 'description',
                  'owner',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Выхода нет')}),
            'group': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Сплин')}),
            'description': forms.Textarea(attrs={'class': 'form-control',
                                                 'placeholder': _(
                                                     "Скоро рассвет, "
                                                     "Выхода нет. "
                                                     "Ключ поверни...")}),
        }


    def clean_name(self):
        return self.cleaned_data['name'].title()


class SearchForm(forms.Form):
    # name = _build_choice_field(_('Name'), models.Song.name)
    # group = _build_choice_field(_('Group'), models.Song.group)

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)

    def clean(self):

        cleaned_data = super(SearchForm, self).clean()

        if not any([cleaned_data['name'],\
                    cleaned_data['group']]):
            raise forms.ValidationError(_('You must select at least one filter'))

song/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.utils.translation import pgettext, ugettext as _
from django.views.decorators.http import require_POST
from django.views.generic import ListView, CreateView, \
    UpdateView, View

from song import forms, models


class SongIndexView(ListView):
    template_name = 'song/index.html'
    context_object_name = 'songs'

    def get_queryset(self):
        return models.Song.objects.select_related('group').order_by('-id')[:12]


def song_detail_view(request, pk_or_slug):
    pet = models.Song.objects.filter(slug=pk_or_slug).first()

    if not song:
        try:
            song = models.Song.objects.get(pk=pk_or_slug)
        except ValueError:
            raise Http404()

    context = {
        'song': song,
        'current_url': request.build_absolute_uri(request.get_full_path()),
    }
    return render(request, 'song/pet_detail.html', context)


def paginate_songs(queryset, page, paginate_by=12):
    """Returns the pets for the current requested page and the page number"""
    paginator = Paginator(queryset, paginate_by)

    try:
        songs = paginator.page(page)
        page = int(page)
    except PageNotAnInteger:
        songs = paginator.page(1)
        page = 1
    except EmptyPage:
        songs = paginator.page(paginator.num_pages)
        page = paginator.num_pages

    return songs, page


def render_song_list(request, queryset):
    songs, page = paginate_songs(queryset, request.GET.get('page'))

    return render(request, 'song/pet_list.html', {
        'songs': songs,
        'current_page': page
    })


class RegisterSongView(LoginRequiredMixin, CreateView):
    template_name = 'song/addSong.html'
    model = models.Song
    form_class = forms.SongForm

    def get_success_url(self):
        return reverse('song:registered', args=[self.object.slug])

    def get(self, request, *args, **kwargs):
        if not request.user.is_information_confirmed:
            messages.warning(request, _('Please confirm your informations before registering a new pet.'))
            return HttpResponseRedirect(reverse('users:edit'))
        else:
            return super(RegisterSongView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(RegisterSongView, self).form_valid(form)


class EditSongView(UpdateView):
    template_name = 'song/edit.html'
    form_class = forms.SongForm
    model = models.Song

    def get(self, request, *args, **kwargs):
        current_song = self.get_object()
        if request.user == current_song.owner:
            return super(EditSongView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(
                reverse('song:detail', kwargs={'pk_or_slug': current_song.slug})
            )

    def form_valid(self, form):
        return super(EditSongView, self).form_valid(form)


@require_POST
def delete_song(request, slug):
    song = get_object_or_404(models.Song, slug=slug)

    if request.user == song.owner:
        song.delete()
        return HttpResponseRedirect(reverse('song:index'))

    return HttpResponseRedirect(song.get_absolute_url())


@require_POST
def change_status(request, slug):
    song = get_object_or_404(models.Pet, slug=slug)

    if request.user != song.owner:
        return HttpResponseRedirect(song.get_absolute_url())

    song.change_status()
    return HttpResponseRedirect(reverse('song:detail', kwargs={'pk_or_slug': song.slug}))


def upload_image(request, slug):
    song = get_object_or_404(models.Pet, slug=slug)
    picture = request.FILES.get('another_picture', False)

    if request.user == song.owner and request.method == 'POST' and picture:
        models.Photo.objects.create(pet_id=song.id, image=picture)

    return HttpResponseRedirect(reverse('song:detail', kwargs={'pk_or_slug': song.slug}))


class SearchView(View):
    def get(self, request):
        return render(request, 'song/search.html', {'form': SearchForm()})

    def post(self, request):
        form = SearchForm(request.POST)

        if not form.is_valid():
            return render(request, 'song/search.html', {'form': form})

        query = self._build_query(form.cleaned_data)

        songs = models.Song.objects.actives().filter(query)
        return render(request, 'song/search.html', {'form': form, 'songs': songs})

    @staticmethod
    def _build_query(cleaned_data):
        query = Q()

        for key, value in cleaned_data.items():
            if value:
                query &= Q(**{key: value})

        return query


def registered(request, slug):
    context = {
        'song_slug': slug,
    }
    return render(request, 'song/registered.html', context)


def poster(request, slug):
    song = get_object_or_404(models.Song, slug=slug)
    return render(request, 'song/poster.html', {'song': song})


def update_register(request, request_key):
    song = get_object_or_404(models.Song, request_key=request_key)
    song.activate()
    return HttpResponseRedirect(song.get_absolute_url())

song/templates/song/_sidemenu.html
<!--
{% load i18n %}
<div class="col-md-2">
  <div class="sidebar">
    <h3 class="title-text">{% trans 'Missing' context 'plural' %}</h3>
    <ul class="nav">
      {% for kind in kind_lost %}
        <li><a href="{% url 'song:lost' kind.slug %}">
          {{ kind }} <span class="badge">{{ kind.num_pets }}</span></a>
        </li>
      {% endfor %}
    </ul>
    <h3 class="title-text">{% trans 'For Adoption' %}</h3>
    <ul class="nav">
      {% for kind in kind_adoption %}
        <li><a href="{% url 'song:adoption' kind.slug %}">
          {{ kind }} <span class="badge">{{ kind.num_pets }}</span></a>
        </li>
      {% endfor %}
    </ul>
  </div>
 -->

song/templates/song/addSong.html
{% extends '_layouts/main.html' %}

{% block title %}
<div class="heading">
  <h3 class="title-text text-center">Добавляем песенку</h3>
</div>
{% endblock %}

{% block content %}
  <div class="row">
    {% include 'song/trackForm.html' %}
  </div>
{% endblock %}

song/templates/song/detail.html
{% extends '_layouts/main.html' %}
{% load static thumbnail %}

<!--{% block metatags %}
  <meta property="og:title" content="{{ song.name }}">
  <meta property="og:description" content="{{ pet.description }}">
  <meta property="og:url" content="{{ current_url }}">
  <meta property="og:image"
        content="http://www.cademeubicho.com{{ pet.profile_picture|thumbnail_url:'pet_thumb' }}">
  <meta property="og:site_name" content="Cadê meu Bicho?">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{{ pet.name }} | Cadê meu Bicho?">
  <meta name="twitter:description" content="{{ pet.description }}">
  <meta name="twitter:image:src"
        content="http://www.cademeubicho.com{{ pet.profile_picture|thumbnail_url:'pet_thumb' }}">
{% endblock %}-->

{% block title %}{{ song.group }} - {{ song.name }}{% endblock %}

{% block content %}
  <div class="modal fade" id="delete_pet" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Delete Track</h4>
        </div>

        <div class="modal-body">
          <p>Do you really want to erase?</p>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>

          <form action="{% url 'song:delete_pet' pet.slug %}" method="post" class="form-inline">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete"/>
          </form>
        </div>

      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-5">
      <a href="{{ pet.profile_picture.url }}" data-lightbox="{{ pet.slug }}" data-title="{{ pet }}">
        <img class="img-thumbnail" src="{{ pet.profile_picture|thumbnail_url:'pet_thumb' }}"
             alt="{{ pet }}"/>
      </a>
      {% if user == pet.owner %}
        <form class="form-horizontal" method="POST" enctype="multipart/form-data"
              action="{% url 'meupet:upload_image' pet.slug %}">
          {% csrf_token %}
          <input name="pet_id" value="{{ pet.id }}" type="hidden">

          <div class="form-group">
            <label for="another_picture" class="control-label">Add Photo</label>
            <input type="file" id="another_picture" name="another_picture">
            <span class="help-block">Maximum image size is 8MB</span>
          </div>
          <div class="form-group">
            <input type="submit" name="submit" class="btn btn-primary pull-right" value="Submit Image}">
          </div>
        </form>
      {% endif %}
    </div>

    <div class="col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            <strong>Description:</strong><br/>
            {{ pet.description }}
          </p>

          <p>
            <strong>City:</strong><br/>
            {{ pet.city|title }}
          </p>

          {% if pet.size %}
            <p>
              <strong>Size:</strong><br/>
              {{ pet.get_size_display }}
            </p>
          {% endif %}

          {% if pet.sex %}
            <p>
              <strong>Sex:</strong><br/>
              {{ pet.get_sex_display }}
            </p>
          {% endif %}

          {% if user == pet.owner %}
            <div class="pull-right">
              {% if not pet.found_or_adopted %}
                <form action="{% url 'meupet:change_status' pet.slug %}" method="post" class="form-inline">
                  {% csrf_token %}
                  <input type="submit" class="btn btn-success" value="
                    {% if pet.status == pet.MISSING %}
                      {% trans 'Mark as found!' %}
                    {% else %}
                      {% trans 'Mark as adopted!' %}
                    {% endif %}
                  "/>
                </form>
              {% endif %}

              <a href="{% url 'meupet:edit' pet.slug %}" class="btn btn-primary">{% trans 'Edit' %}</a>

              <a href="{% url 'meupet:poster' pet.slug %}" class="btn btn-primary">{% trans 'Generate Poster' %}</a>

              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_pet">
                {% trans 'Delete Pet' %}
              </button>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
    {% if pet.photo_set.all %}
      <div class="col-md-12">
        <h3>{% trans 'More photos' %}</h3>

        <div class="row">
          {% for photo in pet.photo_set.all %}
            <div class="col-md-3">
              <a href="{{ photo.image.url }}" data-lightbox="{{ pet.slug }}" data-title="{{ pet }}">
                <img class="img-thumbnail" src="{{ photo.image|thumbnail_url:'pet_thumb' }}"
                     alt="{{ pet }}"/>
              </a>
            </div>
            {% if forloop.counter|divisibleby:4 %}
              </div>
              <div class="row">
            {% endif %}
          {% endfor %}
          </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

song/templates/song/edit.html
{% extends '_layouts/main.html' %}

{% block title %}
<div class="heading">
  <h3 class="title-text text-center">Edit Track</h3>
</div>
{% endblock %}

{% block content %}
  <div class="row">
    {% include 'meupet/trackForm.html' %}
  </div>
{% endblock %}

song/templates/song/index.html
{% extends '_layouts/main.html' %}

{% block title %}<div class="heading">
  <h3 class="title-text text-center">Группы</h3>
</div>
{% endblock %}

{% block body %}
<!--
<ul>
    {% for label in labelsList %}
  <li>
    <a href="{{ label.get_absolute_url }}">
      {{ label.headline}}
    </a>
  <li>
{% endfor %}
</ul>
-->

<div class="labels">
<ul>
  <li><a href="/song/0/">0</a></li>
  <li><a href="/song/1/">1</a></li>
  <li><a href="/song/2/">2</a></li>
  <li><a href="/song/3/">3</a></li>
  <li><a href="/song/4/">4</a></li>
  <li><a href="/song/5/">5</a></li>
  <li><a href="/song/6/">6</a></li>
  <li><a href="/song/7/">7</a></li>
  <li><a href="/song/8/">8</a></li>
  <li><a href="/song/9/">9</a></li>
  <li><a href="/song/a/">A</a></li>
  <li><a href="/song/b/">B</a></li>
  <li><a href="/song/c/">C</a></li>
  <li><a href="/song/d/">D</a></li>
  <li><a href="/song/e/">E</a></li>
  <li><a href="/song/f/">F</a></li>
  <li><a href="/song/g/">G</a></li>
  <li><a href="/song/h/">H</a></li>
  <li><a href="/song/i/">I</a></li>
  <li><a href="/song/j/">J</a></li>
  <li><a href="/song/k/">K</a></li>
  <li><a href="/song/l/">L</a></li>
  <li><a href="/song/m/">M</a></li>
  <li><a href="/song/n/">N</a></li>
  <li><a href="/song/o/">O</a></li>
  <li><a href="/song/p/">P</a></li>
  <li><a href="/song/q/">Q</a></li>
  <li><a href="/song/r/">R</a></li>
  <li><a href="/song/s/">S</a></li>
  <li><a href="/song/t/">T</a></li>
  <li><a href="/song/u/">U</a></li>
  <li><a href="/song/v/">V</a></li>
  <li><a href="/song/w/">W</a></li>
  <li><a href="/song/x/">X</a></li>
  <li><a href="/song/y/">Y</a></li>
  <li><a href="/song/z/">Z</a></li>
</ul>
</div>
{% block content %}
  {% include '_partials/tracksList.html' %}
{% endblock %}
{% endblock body %}

song/templates/song/pet_detail.html
{% extends '_layouts/base.html' %}
{% load i18n static thumbnail %}

{% block metatags %}
  <meta property="og:title" content="{{ pet.name }} | Cadê meu Bicho?">
  <meta property="og:description" content="{{ pet.description }}">
  <meta property="og:url" content="{{ current_url }}">
  <meta property="og:image"
        content="http://www.cademeubicho.com{{ pet.profile_picture|thumbnail_url:'pet_thumb' }}">
  <meta property="og:site_name" content="Cadê meu Bicho?">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{{ pet.name }} | Cadê meu Bicho?">
  <meta name="twitter:description" content="{{ pet.description }}">
  <meta name="twitter:image:src"
        content="http://www.cademeubicho.com{{ pet.profile_picture|thumbnail_url:'pet_thumb' }}">
{% endblock %}

{% block title %}{{ pet.name }} - {{ pet.get_status_display }}{% endblock %}
{% block page_title %}{{ pet.get_status_display }}: {{ pet.name|title }}, {{ pet.city|title }}{% endblock %}

{% block content %}
  <div class="modal fade" id="delete_pet" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">{% trans 'Delete Pet' %}</h4>
        </div>

        <div class="modal-body">
          <p>{% trans 'Do you really want to erase this pet?' %}</p>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cancel' %}</button>

          <form action="{% url 'meupet:delete_pet' pet.slug %}" method="post" class="form-inline">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="{% trans 'Delete' %}"/>
          </form>
        </div>

      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-5">
      <a href="{{ pet.profile_picture.url }}" data-lightbox="{{ pet.slug }}" data-title="{{ pet }}">
        <img class="img-thumbnail" src="{{ pet.profile_picture|thumbnail_url:'pet_thumb' }}"
             alt="{{ pet }}"/>
      </a>
      {% if user == pet.owner %}
        <form class="form-horizontal" method="POST" enctype="multipart/form-data"
              action="{% url 'meupet:upload_image' pet.slug %}">
          {% csrf_token %}
          <input name="pet_id" value="{{ pet.id }}" type="hidden">

          <div class="form-group">
            <label for="another_picture" class="control-label">{% trans 'Add Photo' %}</label>
            <input type="file" id="another_picture" name="another_picture">
            <span class="help-block">{% trans 'Maximum image size is 8MB' %}</span>
          </div>
          <div class="form-group">
            <input type="submit" name="submit" class="btn btn-primary pull-right" value="{% trans 'Submit Image' %}">
          </div>
        </form>
      {% endif %}
    </div>

    <div class="col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            <strong>{% trans 'Description' %}:</strong><br/>
            {{ pet.description }}
          </p>

          <p>
            <strong>{% trans 'City' %}:</strong><br/>
            {{ pet.city|title }}
          </p>

          {% if pet.size %}
            <p>
              <strong>{% trans 'Size' %}:</strong><br/>
              {{ pet.get_size_display }}
            </p>
          {% endif %}

          {% if pet.sex %}
            <p>
              <strong>{% trans 'Sex' %}:</strong><br/>
              {{ pet.get_sex_display }}
            </p>
          {% endif %}

          <p>
            <strong>{% trans 'Contact' %}:</strong><br/>
            <a href="{% url 'users:user_profile' pet.owner.id %}">{{ pet.owner.get_full_name }}</a>
            {% if pet.owner.facebook %} | <a href="{{ pet.owner.facebook }}">Facebook</a>{% endif %}
          </p>

          <p>
            <strong>{% trans 'Share' %}:</strong><br/>
            <a href="http://www.facebook.com/sharer.php?u={{ current_url }}" target="_blank">
              <img src="{% static 'img/facebook.png' %}" alt="Facebook"/>
            </a>
            <a href="http://twitter.com/share?url={{ current_url }}" target="_blank">
              <img src="{% static 'img/twitter.png' %}" alt="Twitter"/>
            </a>
          </p>
          {% if user == pet.owner %}
            <div class="pull-right">
              {% if not pet.found_or_adopted %}
                <form action="{% url 'meupet:change_status' pet.slug %}" method="post" class="form-inline">
                  {% csrf_token %}
                  <input type="submit" class="btn btn-success" value="
                    {% if pet.status == pet.MISSING %}
                      {% trans 'Mark as found!' %}
                    {% else %}
                      {% trans 'Mark as adopted!' %}
                    {% endif %}
                  "/>
                </form>
              {% endif %}

              <a href="{% url 'meupet:edit' pet.slug %}" class="btn btn-primary">{% trans 'Edit' %}</a>

              <a href="{% url 'meupet:poster' pet.slug %}" class="btn btn-primary">{% trans 'Generate Poster' %}</a>

              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_pet">
                {% trans 'Delete Pet' %}
              </button>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
    {% if pet.photo_set.all %}
      <div class="col-md-12">
        <h3>{% trans 'More photos' %}</h3>

        <div class="row">
          {% for photo in pet.photo_set.all %}
            <div class="col-md-3">
              <a href="{{ photo.image.url }}" data-lightbox="{{ pet.slug }}" data-title="{{ pet }}">
                <img class="img-thumbnail" src="{{ photo.image|thumbnail_url:'pet_thumb' }}"
                     alt="{{ pet }}"/>
              </a>
            </div>
            {% if forloop.counter|divisibleby:4 %}
              </div>
              <div class="row">
            {% endif %}
          {% endfor %}
          </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

song/templates/song/pet_list.html
{% extends '_layouts/main.html' %}

{% block title %}{{ kind }} - {{ status }}{% endblock %}

{% block content %}
  {% include '_partials/trackList.html' %}
{% endblock %}