api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
    url(r'^pets/$', views.ListSongs.as_view(), name='list_songs'),
    url(r'^cities/$', views.GroupList.as_view(), name='list_song'),
]

pets/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.contrib import admin


urlpatterns = [
    url(r'^pets/', include('song.urls', namespace='song')),
    url(r'^social/', include('social_django.urls', namespace='social')),
    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('common.urls', namespace='common')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

song/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.SongIndexView.as_view(), name='index'),
    url(r'^new/$', views.RegisterSongView.as_view()),
    url(r'^search/$', views.SearchView.as_view()),
    url(r'^novo/$', views.RegisterSongView.as_view(), name='register'),
    url(r'^busca/$', views.SearchView.as_view(), name='search'),
    url(r'^atualizar-cadastro/(?P<request_key>\w+)/$', views.update_register, name='update_register'),
    url(r'^pet/(?P<slug>[-\w]*)/foto/$', views.upload_image, name='upload_image'),
    url(r'^(?P<slug>[-\w]*)/editar/$', views.EditSongView.as_view(), name='edit'),
    url(r'^(?P<slug>[-\w]*)/poster/$', views.poster, name='poster'),
    url(r'^(?P<slug>[-\w]*)/editar/situacao/$', views.change_status, name='change_status'),
    url(r'^(?P<slug>[-\w]*)/deletar/$', views.delete_song, name='delete_pet'),
    url(r'^(?P<slug>[-\w]*)/registrado/$', views.registered, name='registered'),

    url(r'^(?P<pk_or_slug>[-\w]*)/$', views.song_detail_view, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.song_detail_view, name='detail_by_pk'),
]

users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.CreateUserView.as_view(), name='create'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.ProfileDetailView.as_view(), name='user_profile'),
    url(r'^profile/$', views.UserProfileView.as_view(), name='profile'),
    url(r'^profile/edit/$', views.EditUserProfileView.as_view(), name='edit'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^confirm/$', views.confirm_information, name='confirm_information'),
    url(r'^recover/$', views.RecoverView.as_view(), name='recover_password'),
    url(r'^recover/reset/done/$', views.RecoverResetDoneView.as_view(), name='recover_password_done'),
    url(r'^recover/reset/(?P<token>.+)/$', views.RecoverResetView.as_view(), name='recover_password_reset'),
    url(r'^recover/(?P<signature>.+)/$', views.RecoverDoneView.as_view(), name='recover_password_sent'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from users.validators import validate_facebook_url
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
import os


class OwnerProfile(AbstractUser):
    is_information_confirmed = models.BooleanField(default=False)
    facebook = models.URLField(max_length=250, blank=True, null=True,
                               validators=[validate_facebook_url])
    phone = models.CharField('Telefone', max_length=30, blank=True)
    profile_picture = models.ImageField(upload_to='user_profiles',
                                        help_text=_('Maximum image size is 8MB'),
                                        default=os.path.dirname(os.path.dirname(os.path.dirname(__file__))) + '/static/img/caaaat.png')

    def get_absolute_url(self):
        return reverse('users:user_profile', args=[self.id])

    def __str__(self):
        return self.username
# CREATE TABLE test_users (id int, first_name VARCHAR(50), second_name VARCHAR(50), mail VARCHAR(50), count_songs int);

# class Musicants(AbstractUser):
#     f_name = models.CharField(max_length=50)
#     s_name = models.CharField(max_length=50)
#     mail = models.CharField(max_length=50)
#     count_songs = models.CharField(max_length=50)

users/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from password_reset.forms import PasswordRecoveryForm, PasswordResetForm

from users.models import OwnerProfile


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'autofocus': 'autofocus'})
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})


class UserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        self.fields['facebook'].help_text = _(
            'Click <a href="#" data-toggle="modal" data-target="#ajuda-facebook">'
            'here</a> to get help filling this field.')
        self.fields['phone'].widget.attrs.update({'class': 'form-control'})


class RegisterForm(UserForm):
    password1 = forms.CharField(label=_('Password'), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_('Password confirmation'), widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})

        self.fields['profile_picture'].widget.attrs.update({'class': 'form-control'})

        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['facebook'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})
        self.fields['facebook'].widget.attrs.update(
            {'placeholder': _('Enter the full address for your Facebook profile.')})

        self.fields['username'].help_text = _('Required. 30 characters or less. '
                                              'Only letters, numbers e @/./+/-/_.')

    class Meta:
        model = OwnerProfile
        fields = ('first_name', 'last_name', 'profile_picture',  'email', 'username',
                  'facebook', 'phone', 'password1', 'password2',)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("The two password fields didn't match."))
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UpdateUserForm(UserForm):
    class Meta:
        model = OwnerProfile
        fields = ('first_name', 'last_name', 'profile_picture', 'email', 'facebook', 'phone',)

    def __init__(self, *args, **kwargs):
        super(UpdateUserForm, self).__init__(*args, **kwargs)
        self.helper.add_input(Submit('submit', _('Save Changes')))

    def save(self, commit=True):
        self.instance.is_information_confirmed = True
        super(UpdateUserForm, self).save()


class UsersPasswordRecoveryForm(PasswordRecoveryForm):
    def __init__(self, *args, **kwargs):
        super(UsersPasswordRecoveryForm, self).__init__(*args, **kwargs)
        self.fields['username_or_email'].label = ''
        self.helper = FormHelper()
        self.helper.add_input(Submit('recover', _('Recover password')))


class UsersPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UsersPasswordResetForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('recover', _('Recover password')))

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse, reverse_lazy
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, resolve_url
from django.template.context import RequestContext
from django.utils.http import is_safe_url
from django.views.generic import CreateView, TemplateView, UpdateView, DetailView
from django.utils.translation import ugettext as _

from password_reset.views import Recover, RecoverDone, Reset, ResetDone

from users.forms import LoginForm, RegisterForm, UpdateUserForm, UsersPasswordRecoveryForm, UsersPasswordResetForm
from users.models import OwnerProfile


class RecoverView(Recover):
    template_name = 'users/recover.html'
    form_class = UsersPasswordRecoveryForm
    success_url_name = 'users:recover_password_sent'
    email_template_name = 'users/recover_email.txt'
    search_fields = ['username', 'email']


class RecoverDoneView(RecoverDone):
    template_name = 'users/recover.html'


class RecoverResetView(Reset):
    template_name = 'users/reset.html'
    success_url = 'users:recover_password_done'
    form_class = UsersPasswordResetForm
    token_expires = 3600 * 2


class RecoverResetDoneView(ResetDone):
    template_name = 'users/reset_done.html'


class CreateUserView(CreateView):
    model = OwnerProfile
    form_class = RegisterForm
    template_name = 'users/create.html'
    authenticated_redirect_url = reverse_lazy('song:index')

    msg = _('Your account has been successfully created, access <a href="{0}">'
            'this page</a> and register the pet :)')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(resolve_url(self.authenticated_redirect_url))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.is_information_confirmed = True
        return super(CreateUserView, self).form_valid(form)

    def get_success_url(self):
        url = reverse('song:register')
        messages.success(self.request, self.msg.format(url))
        user = authenticate(
            username=self.request.POST.get('username'),
            password=self.request.POST.get('password1')
        )
        login(self.request, user)
        return reverse('song:index')


class EditUserProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/edit_profile.html'
    model = OwnerProfile
    form_class = UpdateUserForm

    def get_success_url(self):
        messages.success(self.request, _('Changes saved successfully.'))
        return reverse('song:index')

    def get_object(self, queryset=None):
        return self.request.user


def user_login(request):
    context = RequestContext(request)

    redirect_to = request.POST.get('next', request.GET.get('next', ''))

    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.data.get('username'),
                                password=form.data.get('password'))
            if user and user.is_active:
                login(request, user)

                if is_safe_url(redirect_to):
                    return HttpResponseRedirect(redirect_to)

                return HttpResponseRedirect(reverse('song:index'))
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form}, context)


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('song:index'))


class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['object'] = self.request.user
        context['pets'] = self.request.user.song_set.all()
        return context


class ProfileDetailView(DetailView):
    template_name = 'users/profile.html'
    model = OwnerProfile

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        context['pets'] = self.object.song_set.all()
        return context


def confirm_information(request):
    """ This check that the user has confirmed the information and
    redirect to the correct view"""
    if request.user:
        if request.user.is_information_confirmed:
            return HttpResponseRedirect(reverse('song:index'))
        else:
            return HttpResponseRedirect(reverse('users:edit'))

users/templates/users/create.html
{% extends '_layouts/main.html' %}

{% block title %}
<div class="heading">
  <h3 class="title-text text-center">Создай аккаунт</h3>
</div>
{% endblock%}
{% block body %}
  <form method="post">
    {% csrf_token %}
    <div class="form-group{% if form.first_name.errors %} has-error{% endif %}">
      <label for="{{ form.first_name.id_for_label }}" class="control-label">Имя</label>
      <div class="controls">
        {{ form.first_name }}
        {{ form.first_name.errors }}
      </div>
    </div>
    <div class="form-group{% if form.last_name.errors %} has-error{% endif %}">
      <label for="{{ form.last_name.id_for_label }}" class="control-label">Фамилия</label>
      <div class="controls">
        {{ form.last_name }}
        {{ form.last_name.errors }}
      </div>
    </div>
    <div class="form-group{% if form.email.errors %} has-error{% endif %}">
      <label for="{{ form.email.id_for_label }}" class="control-label">Email</label>
      <div class="controls">
        {{ form.email }}
        {{ form.email.errors }}
      </div>
    </div>
    <div class="form-group{% if form.username.errors %} has-error{% endif %}">
      <label for="{{ form.username.id_for_label }}" class="control-label">Логин</label>
      <div class="controls">
        {{ form.username }}
        <div class="help-block">{{ form.username.help_text }}</div>
        {{ form.username.errors }}
      </div>
    </div>
    <div class="form-group{% if form.password1.errors %} has-error{% endif %}">
      <label for="{{ form.password1.id_for_label }}" class="control-label">Пароль</label>
      <div class="controls">
        {{ form.password1 }}
        {{ form.password1.errors }}
      </div>
    </div>
    <div class="form-group{% if form.password2.errors %} has-error{% endif %}">
      <label for="{{ form.password2.id_for_label }}" class="control-label">Подтвердите пароль</label>
      <div class="controls">
        {{ form.password2 }}
        {{ form.password2.errors }}
      </div>
    </div>
    <div class="form-group">
      <input type="submit" name="submit" class="btn btn-primary" value=Create>
    </div>
  </form>
{% endblock body %}

users/templates/users/editProfile.html
{% extends '_layouts/main.html' %}
{% load crispy_forms_tags static %}

{% block title %}
<div class="heading">
  <h3 class="title-text text-center">Edit Profile</h3>
</div>
{% endblock %}

{% block content %}
  <h4>Это ты!</h4>
  {% crispy form %}
{% endblock %}

users/templates/users/edit_profile.html
{% extends '_layouts/base.html' %}
{% load i18n crispy_forms_tags static %}

{% block title %}{% trans 'Edit Profile' %}{% endblock %}

{% block content %}
  <div id="ajuda-facebook" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span
              aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">{% trans 'Find your Facebook profile address' %}</h4>
        </div>
        <div class="modal-body">
          <ol>
            <li>
              <p>{% trans 'On Facebook, find your name in the top navigation bar and click on it.' %}</p>

              <p><img class="img-responsive" src="{% static 'img/kdmeubicho_nome.png' %}"
                      alt="{% trans "Facebook's navigation bar" %}"></p>
            </li>
            <li>
              <p>{% trans "After the page loads your profile address will be in your browser's address bar." %}</p>

              <p><img class="img-responsive" src="{% static 'img/kdmeubicho_endereco.png' %}"
                      alt="{% trans "Browser's address bar" %}"></p>
            </li>
            <li>
              <p>{% trans 'Copy and paste the address in the form field' %}</p>

              <p><img class="img-responsive" src="{% static 'img/kdmeubicho_form.png' %}"
                      alt="{% trans 'Filled form' %}"></p>
            </li>
          </ol>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
        </div>
      </div>
    </div>
  </div>

  <h4>{% trans 'Your Profile' %}</h4>
  {% crispy form %}
{% endblock %}

users/templates/users/login.html
{% extends '_layouts/main.html' %}
{% load static %}

{% block title %}
<div class="heading">
  <h3 class="title-text text-center">Заходи, мяу</h3>
</div>
{% endblock %}

{% block body %}
  <div class="col-md-4 col-md-offset-4">
    <form method="post">
      {{ form.non_field_errors }}
      {% csrf_token %}
      <div class="form-group{% if form.username.errors %} has-error{% endif %}">
        <label for="{{ form.username.id_for_label }}" class="control-label">{{ form.username.label }}</label>
        <div class="controls">
          {{ form.username }}
          {{ form.username.errors }}
        </div>
      </div>
      <div class="form-group{% if form.password.errors %} has-error{% endif %}">
        <label for="{{ form.password.id_for_label }}" class="control-label">{{ form.password.label }}</label>
        <div class="controls">
          {{ form.password }}
          {{ form.password.errors }}
        </div>
      </div>
      <div class="form-group">
        <div class="controls">
          <input class="btn btn-primary btn-block" type="submit" value="Login" name="login">
        </div>
      </div>
    </form>
    <a href="{% url 'users:recover_password' %}">Забыли пароль?</a>
  </div>
{% endblock body %}

users/templates/users/profile.html
{% extends '_layouts/main.html' %}
{% load  static %}

{% block body %}
<div class ="container">
  <div class="container">
  <img class = "profile-photo" src="{% static 'img/no-photo.png' %}">
  <div class="info-block">
    <div class ="page-block row">
      <div class="name col-md-11">{{ object.first_name }} {{ object.last_name }}</div>
      {% if user.is_authenticated and user.id == object.id %}
      <a href="{% url 'users:edit' %}" class="btn btn-primary col-md-1">Edit</a>
      {% endif %}
    </div>
    <div class="page-block">
      <ul class = "user-box">
        <li>
          <a href="Favorites" >
            <img class= "img-icon" src = "{% static 'img/favourite.png' %}">
            Favorites
          </a>
        </li>
        <li >
          <a href="ADDed">
            <img class= "img-icon" src = "{% static 'img/star.png' %}">
            ADDed
          </a>
        </li>
      </ul>
    </div>
  </div>
  </div>
  <div class =" container page-block">
  <a href="{% url 'song:register' %}">Add track</a>
  <h4>Добавленные треки</h4>
  <!-- добавить добавленные-->
  </div>
</div>
{% endblock %}

users/templates/users/recover.html
{% extends '_layouts/main.html' %}
{% load crispy_forms_tags %}

{% block title %}Recover password{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-7 col-md-offset-1">
      {% if form %}
        <p>
          Enter your email address or username.
        </p>
        {% crispy form %}
      {% else %}
        <p>
          An email has just been sent to' <strong>{{ email }}</strong>.
        </p>
        <p>
          Use the link in this email to set up a new password.
        </p>
        <p>
          <a class="btn btn-primary" href="{% url 'meupet:index' %}" title="Back to home page">
            Back to home page
          </a>
        </p>
      {% endif %}
    </div>
  </div>
{% endblock %}

users/templates/users/reset.html
{% extends '_layouts/main.html' %}
{% load crispy_forms_tags %}

{% block title %}Recover password{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-6 col-md-offset-1">
      <p>
        Enter a new password.
      </p>
      <p>
        {% blocktrans %}If you forgot, your username is <strong>{{ username }}</strong>.{% endblocktrans %}
      </p>
      {% crispy form %}
    </div>
  </div>
{% endblock %}

users/templates/users/reset_done.html
{% extends '_layouts/main.html' %}

{% block title %}Recover password{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-11 col-md-offset-1">
      <p>Your password has been successfully changed.</p>
      <p>
        {% url 'users:login' as page_url %}
        {% blocktrans %}Click <a href="{{ page_url }}">here</a> to login into your account.{% endblocktrans %}
      </p>
    </div>
  </div>
{% endblock %}